---
title: "10-DESeq"
output: html_document
---

```{bash}
curl -o ../data/kallisto-0315.isoform.counts.matrix https://raw.githubusercontent.com/sr320/nb-2020/master/C_bairdi/analyses/kallisto-0315.isoform.counts.matrix
```

```{bash}
head ../data/kallisto-0315.isoform.counts.matrix
```

```{r}
library(DESeq2)
```


```{r}
d19 <- read.table("../data/kallisto-0315.isoform.counts.matrix", header = T, sep = "\t")
rownames(d19) <- d19$Feature
d19 <- d19[,-1]
head(d19)
```

```{r}
library(tidyverse)
```

```{r}
d19 <- select(d19, X329774_out, X329776_out, X329775_out, X329777_out)
```

```{r}
head(d19)
```

```{r}
d19 %>% mutate_if(is.numeric, round, 0)
```



```{r}
head(d19)
```



```{r}
deseq2.colData <- data.frame(condition=factor(c(rep("Treated", 2), rep("Control", 2))), 
                             type=factor(rep("paired-end", 4)))
rownames(deseq2.colData) <- colnames(data)
deseq2.dds <- DESeqDataSetFromMatrix(countData = d19,
                                     colData = deseq2.colData, 
                                     design = ~ condition)
```


```{r}
deseq2.dds <- DESeq(deseq2.dds)
deseq2.res <- results(deseq2.dds)
deseq2.res <- deseq2.res[order(rownames(deseq2.res)), ]
```

```{r}
head(deseq2.res)
```





