---
title: "10-DESeq"
output: html_document
---


```{r}
library(DESeq2)
```


```{r}
d19 <- read.table("../data/kallisto-0315.isoform.counts.txt", header = T, sep = "\t")
rownames(d19) <- d19$Feature
d19 <- d19[,-1]
head(d19)
```



```{r}
deseq2.colData <- data.frame(condition=factor(c(rep("Treated", 2), rep("Control", 2))), 
                             type=factor(rep("paired-end", 4)))
rownames(deseq2.colData) <- colnames(data)
deseq2.dds <- DESeqDataSetFromMatrix(countData = d19,
                                     colData = deseq2.colData, 
                                     design = ~ condition)
```


```{r}
deseq2.dds <- DESeq(deseq2.dds)
deseq2.res <- results(deseq2.dds)
deseq2.res <- deseq2.res[order(rownames(deseq2.res)), ]
```

```{r}
head(deseq2.res)
```

```{r}
# Count number of hits with adjusted p-value less then 0.05
dim(deseq2.res[!is.na(deseq2.res$padj) & deseq2.res$padj <= 0.05, ])

```


```{r}
tmp <- deseq2.res
# The main plot
plot(tmp$baseMean, tmp$log2FoldChange, pch=20, cex=0.45, ylim=c(-3, 3), log="x", col="darkgray",
     main="Infection  (pval <= 0.05)",
     xlab="mean of normalized counts",
     ylab="Log2 Fold Change")
# Getting the significant points and plotting them again so they're a different color
tmp.sig <- deseq2.res[!is.na(deseq2.res$padj) & deseq2.res$padj <= 0.05, ]
points(tmp.sig$baseMean, tmp.sig$log2FoldChange, pch=20, cex=0.45, col="red")
# 2 FC lines
abline(h=c(-1,1), col="blue")
```

```{r}
write.table(tmp.sig, "../analyses//2019-infection_DEGlist.tab", row.names = T)

```


```{bash}
head ../analyses//2019-infection_DEGlist.tab
```

```{bash}
wc -l ../analyses//2019-infection_DEGlist.tab
```